### ISSUE TITLE
Error with SQANTI-SIM tutorial Evaluation step

### ISSUE THREAD

**Issue by jkmh2** [ConesaLab/SQANTI-SIM#1]
Hello,

I am working through the SQANTI-SIM tutorial and I encountered an error with the evaluation step.  

######### Running the eval step
First I loaded the SQANTI-SIM conda environment:
**$ conda activate SQANTI-SIM.env**

Then I made sure that the following PYTHONPATHs were available:
**$ echo $PYTHONPATH
/project/rainbow_trout/cDNA_Cupcake:/project/rainbow_trout/cDNA_Cupcake/sequence**

and the PATH to SQANTI-SIM:
**$ echo $PATH
/home/john.konvalina/.conda/envs/SQANTI-SIM.env/bin:/software/el9/apps/miniconda/4.12.0/condabin:/home/john.konvalina/.local/bin:/home/john.konvalina/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/project/rainbow_trout/Konvalina_rainbow_trout_genome/pbsim3-master/bin:/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM**

Finally, I ran the following bash script:

#!/bin/bash
#SBATCH -o step5.out
#SBATCH -e step5.err

sqanti-sim.py eval \
    --transcriptome longread_transcriptome.isoforms.gtf \
    --gtf design_modified.gtf \
    --genome Homo_sapiens.GRCh38.dna.chromosome.12.fa \
    -i design_index.tsv \
    -d tutorial_eval \
    --min_support 3

#########################
###### Error Message
This is the error message I received after running the bash script:

**$ more step5.err 
WARNING: output directory /project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM_analyses/sqanti-sim_tutorial/step_5_evaluation/tutorial_eval/sqanti3 already exists. Overwriting!
Error corrected FASTA /project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM_analyses/sqanti-sim_tutorial/step_5_evaluation/tutorial_eval/sqanti3/sqanti-sim_corrected.fasta already exists. Using it...
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
**** Parsing Isoforms....
**** RT-switching computation....
Full-length read abundance files not provided.
Isoforms expression files not provided.
**** Writing output files....
Removing temporary files....
SQANTI3 complete in 13.092386850970797 sec.
Warning message:
In inner_join(data.query, idx, by = c("junctions", "chrom")) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 8 of `x` matches multiple rows in `y`.
ℹ Row 48 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.
Warning message:
In inner_join(data.query, idx, by = c("junctions", "chrom")) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 8 of `x` matches multiple rows in `y`.
ℹ Row 71 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.
Error in `[.data.frame`(data.index, data.index[, "sim_counts"] > 0, c("transcript_id",  : 
  undefined columns selected
Calls: [ -> [.data.frame
Execution halted
Traceback (most recent call last):
  File "/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/sqanti-sim.py", line 498, in <module>
    res = eval(input)
  File "/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/sqanti-sim.py", line 449, in eval
    evaluation_metrics.sqanti3_stats(args)
  File "/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/src/evaluation_metrics.py", line 233, in sqanti3_stats
    if subprocess.check_call(cmd, shell=True) != 0:
  File "/home/john.konvalina/.conda/envs/SQANTI-SIM.env/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'Rscript /project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/src/SQANTI-SIM_report.R tutorial_eval/sqanti3/sqanti-sim_classification.txt tutorial_eval/sqanti3/sqa
nti-sim_junctions.txt design_index.tsv 3 /project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/src none' returned non-zero exit status 1.**

#####################

From my interpretation, the "subprocess.py" script releases an error called a "CalledProcessError".  However, I'm not sure what caused that error.  I looked at the lines mentioned in the Traceback list but couldn't find anything that would lead to an error.  

It seems that the error has to do with the data.frame:
**Error in `[.data.frame`(data.index, data.index[, "sim_counts"] > 0, c("transcript_id",  : 
  undefined columns selected**

However, I'm not sure what data.frame this is in reference to.  It seems that the number of columns does not match the number of rows:

**Warning message:
In inner_join(data.query, idx, by = c("junctions", "chrom")) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 8 of `x` matches multiple rows in `y`.
ℹ Row 48 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.
Warning message:
In inner_join(data.query, idx, by = c("junctions", "chrom")) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 8 of `x` matches multiple rows in `y`.
ℹ Row 71 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.**

I'm not sure which files it is referring to that do not have a matching number of rows and columns.

Thank you for any help that you can provide me.

**Comment by jmestret** [comment]
Hi @jkmh2,

Sorry for the delay in getting back to you. I wanted to let you know that the issue you mentioned has been addressed with the recent changes I've implemented. The problem was related to report generation in R, where it was attempting to access columns that didn't exist in a dataframe, specifically, it was looking for CAGE and short-read data when they were not provided.

You can download the latest version, **v0.2.1**, which includes a patch to resolve this issue, along with a few minor improvements and fixes that I've recently made.

Moreover, I've spiced up the [tutorial](https://github.com/ConesaLab/SQANTI-SIM/wiki/Tutorial) on our wiki to make it more user-friendly and comprehensive. Feel free to give it a try; I'm sure you'll find it super helpful!:satisfied:

I hope this resolves the problem you were facing. Additionally, if you have any more questions or encounter any other issues, please feel free to reach out. 

Best,

Jorge
