### ISSUE TITLE
ValueError: Total of weights must be greater than zero

### ISSUE THREAD

**Issue by jkmh2** [ConesaLab/SQANTI-SIM#3]
Hi there,

I was running the second step of the SQANTI-SIM pipeline (design) and encountered the following error message:

Traceback (most recent call last):
  File "/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/sqanti-sim.py", line 490, in <module>
    res = design(input)
  File "/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/sqanti-sim.py", line 248, in design
    counts_end = design_simulation.simulate_gtf(args)
  File "/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/src/design_simulation.py", line 250, in simulate_gtf
    target = target_trans(args.trans_index, f_idx_out, counts)
  File "/project/rainbow_trout/Konvalina_rainbow_trout_genome/SQANTI-SIM/src/design_simulation.py", line 77, in target_trans
    SC = random.choices(categories, weights=weight_list, k=1)
  File "/home/john.konvalina/.conda/envs/SQANTI-SIM.env/lib/python3.10/random.py", line 535, in choices
    raise ValueError('Total of weights must be greater than zero')
ValueError: Total of weights must be greater than zero

I looked in the python scripts listed, yet I still count not understand what "ValueError: Total of weights must be greater than zero" means. 

Here is the script I ran for the design step:

sqanti-sim.py design sample \
    -i sqanti-sim_index.tsv \
    --gtf $gtf/$gtf_file \
    --genome $Ref_genome/$ref_genome_file \
    --pb \
    --trans_number 3000 \
    --ISM 400 --NIC 400 --NNC 400 \
    --seed 1234

Has anyone else encountered this error before?  Thank you for any help you can provide me.

**Comment by jmestret** [comment]
Hi @jkmh2,

I've been giving some thought to the bug you mention, and I believe I've identified the possible cause. Out of curiosity, are you working with a relatively small GTF annotation file? I've pushed some changes to GitHub, and I'm hopeful these will resolve the issue. 🚀

If these changes have indeed fixed the problem, it would be fantastic if you could close the issue. However, if the issue persists, I'd greatly appreciate it if you could share the Classification Summary Table generated during the classification step (_classif_). If you're comfortable with it, feel free to send me your files so I can try to reproduce the error and address it directly.

I hope I have solved your issue.

Best regards,
Jorge :smiley:

**Comment by jkmh2** [comment]
Hi Jorge,

I redownloaded and installed SQANTI-SIM.  Then, I re-ran step 1 (classify) and step 2 (design).  Good news! It worked!  Thank you for taking the time to address this issue.  I really appreciate it.  I will close the issue now.

@jkmh2
