### ISSUE TITLE
number of simulated isoform incorrect in the final report html

### ISSUE THREAD

**Issue by alexyfyf** [ConesaLab/SQANTI-SIM#5]
Hi team,

I found the number of simulated isoforms incorrect in the final report HTML.
The reason is multiple discovered isoforms can map to the same simulated transcripts, so adding extra rows in your final tsv.
For example

```
> df1 <- read.table('sqanti_eval/sqanti-sim_index_meta.eval.tsv', header = T, sep = '\t')
> df1[5302:5303, c(1:5,14:19)]
          transcript_id            gene_id structural_category    associated_gene associated_trans sim_type requested_counts requested_tpm sim_counts illumina_counts pipeline_performance
5302 ENST00000311852.11 ENSG00000157227.14    novel_in_catalog ENSG00000157227.14            novel    known            64435      2165.128      14262           42788             tx_26770
5303 ENST00000311852.11 ENSG00000157227.14    novel_in_catalog ENSG00000157227.14            novel    known            64435      2165.128      14262           42788             tx_26839
```

could you look into it? Is this expected behavior or not? Will the FP/FN calculation be affected?

Cheers,
Alex

**Comment by jmestret** [comment]
Hi @alexyfyf,

Thanks for letting us know about this issue. I've made some adjustments to the metrics to ensure the metrics now reflect non-redundant true positives (TP). Additionally, I've incorporated redundancy metrics to provide a more comprehensive analysis.

Now, the latest version (**v0.2.2**) includes these fixes, so you can download it and give it a try. We really appreciate you helping us fine-tune SQANTI-SIM. 

Let us know if there's anything else we can help with.

Best regards,
Jorge :smile:
